SHELL := /bin/zsh

# ── Detect local LAN IP (cross-platform via Python3, already required) ─────────
LAN_IP := $(shell python3 -c "import socket; s=socket.socket(socket.AF_INET,socket.SOCK_DGRAM); s.connect(('8.8.8.8',80)); print(s.getsockname()[0]); s.close()" 2>/dev/null)

BACKEND_PORT  ?= 8000
FRONTEND_PORT ?= 5173

.PHONY: help setup-env install docker-dev db-up backend-dev frontend-dev \
        dev-lan lan-clean lint typecheck test check

# ── Help ──────────────────────────────────────────────────────────────────────
help:
	@printf "Available targets:\n"
	@printf "  make setup-env      Copy .env.example to .env if missing\n"
	@printf "  make install        Install frontend and backend dependencies\n"
	@printf "  make docker-dev     Start db, backend and frontend with Docker\n"
	@printf "  make db-up          Start only PostgreSQL/PostGIS\n"
	@printf "  make backend-dev    Run FastAPI locally on :8000\n"
	@printf "  make frontend-dev   Run Vite locally on :5173\n"
	@printf "  make dev-lan        Run full app accessible from local network (auto-detects IP)\n"
	@printf "  make lan-clean      Remove LAN config files generated by dev-lan\n"
	@printf "  make lint           Run frontend lint and backend ruff\n"
	@printf "  make typecheck      Run frontend typecheck\n"
	@printf "  make test           Run backend tests\n"
	@printf "  make check          Run lint, typecheck and tests\n"

# ── Standard setup ────────────────────────────────────────────────────────────
setup-env:
	@if [ ! -f .env ] && [ -f .env.example ]; then cp .env.example .env; echo ".env created from .env.example"; else echo ".env already exists or .env.example missing"; fi

install:
	npm install
	cd apps/backend && python3 -m pip install -e ".[dev]"

docker-dev:
	docker compose up --build

db-up:
	docker compose up -d db

backend-dev:
	cd apps/backend && uvicorn app.main:app --reload --host 0.0.0.0 --port $(BACKEND_PORT)

frontend-dev:
	npm run dev --workspace @atmos/frontend

# ── LAN mode: acceso por IP de red local ──────────────────────────────────────
dev-lan:
	@if [ -z "$(LAN_IP)" ]; then \
	  echo "ERROR: No se pudo detectar la IP de red. Asegurate de estar conectado a una red."; \
	  exit 1; \
	fi
	@echo "---------------------------------------------------"
	@echo "IP detectada : $(LAN_IP)"
	@echo "Backend      : http://$(LAN_IP):$(BACKEND_PORT)"
	@echo "Frontend     : http://$(LAN_IP):$(FRONTEND_PORT)"
	@echo "---------------------------------------------------"
	@echo ""
	@# ── 1. Generar apps/backend/.env con CORS ampliado ──────────────────
	@echo "Configurando CORS para la red local..."
	@{ \
	  grep -v '^CORS_ORIGINS\|^COMPOSE_PROJECT_NAME' .env 2>/dev/null || true; \
	  echo ""; \
	  echo "# Generado automaticamente por 'make dev-lan' - no editar a mano"; \
	  printf 'CORS_ORIGINS=["http://localhost:$(FRONTEND_PORT)","http://127.0.0.1:$(FRONTEND_PORT)","http://$(LAN_IP):$(FRONTEND_PORT)"]\n'; \
	} > apps/backend/.env
	@echo "  OK  apps/backend/.env actualizado"
	@# ── 2. Generar apps/frontend/.env.local con la URL del backend ───────
	@echo "Configurando URL del backend para el frontend..."
	@printf "# Generado automaticamente por 'make dev-lan' - no editar a mano\n" > apps/frontend/.env.local
	@printf "VITE_API_BASE_URL=http://$(LAN_IP):$(BACKEND_PORT)\n" >> apps/frontend/.env.local
	@echo "  OK  apps/frontend/.env.local actualizado"
	@echo ""
	@echo "Iniciando backend y frontend... (Ctrl+C para detener ambos)"
	@echo ""
	@# ── 3. Levantar backend y frontend en paralelo ───────────────────────
	@trap 'echo ""; echo "Deteniendo servidores..."; kill 0' INT; \
	( \
	  cd apps/backend && \
	  .venv/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port $(BACKEND_PORT) \
	) & \
	( \
	  cd apps/frontend && \
	  npx vite --host 0.0.0.0 --port $(FRONTEND_PORT) \
	) & \
	wait

lan-clean:
	@echo "Eliminando archivos de configuracion LAN..."
	@rm -f apps/backend/.env apps/frontend/.env.local
	@echo "  OK  apps/backend/.env eliminado"
	@echo "  OK  apps/frontend/.env.local eliminado"

# ── QA ────────────────────────────────────────────────────────────────────────
lint:
	npm run lint --workspace @atmos/frontend
	cd apps/backend && ruff check .

typecheck:
	npm run typecheck --workspace @atmos/frontend

test:
	cd apps/backend && pytest -q

check: lint typecheck test
