import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { AlertCircle, CheckCircle2 } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

interface ResetPasswordValues {
  token: string;
  newPassword: string;
  confirmPassword: string;
}

interface ResetPasswordProps {
  initialToken?: string;
  onReset: (payload: { token: string; new_password: string }) => Promise<void>;
  onBackToLogin: () => void;
}

export function ResetPassword({ initialToken, onReset, onBackToLogin }: ResetPasswordProps) {
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const form = useForm<ResetPasswordValues>({
    defaultValues: {
      token: initialToken ?? '',
      newPassword: '',
      confirmPassword: '',
    },
  });

  const submit = form.handleSubmit(async (values) => {
    setMessage(null);
    setError(null);

    if (values.newPassword !== values.confirmPassword) {
      form.setError('confirmPassword', { message: 'Password confirmation does not match.' });
      setError('Revisa los campos marcados antes de continuar.');
      return;
    }

    try {
      await onReset({ token: values.token.trim(), new_password: values.newPassword });
      setMessage('Password reset complete. You can now sign in.');
      form.reset({ token: '', newPassword: '', confirmPassword: '' });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not reset password.');
    }
  });

  return (
    <div className="min-h-screen bg-[#F9FBFC] flex items-center justify-center p-4">
      <Card className="w-full max-w-md bg-white shadow-lg">
        <CardHeader className="space-y-2 text-center">
          <CardTitle>Reset Password</CardTitle>
          <CardDescription>Use the one-time token generated by the recovery flow.</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={(e) => void submit(e)} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="reset-token">Reset token</Label>
              <Input
                id="reset-token"
                {...form.register('token', {
                  required: 'Token is required.',
                  minLength: { value: 10, message: 'Invalid token length.' },
                })}
              />
              {form.formState.errors.token && (
                <p className="text-sm text-red-600">{form.formState.errors.token.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="new-password">New password</Label>
              <Input
                id="new-password"
                type="password"
                {...form.register('newPassword', {
                  required: 'New password is required.',
                  minLength: { value: 8, message: 'Minimum 8 characters.' },
                  maxLength: { value: 128, message: 'Maximum 128 characters.' },
                })}
              />
              {form.formState.errors.newPassword && (
                <p className="text-sm text-red-600">{form.formState.errors.newPassword.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="confirm-password">Confirm password</Label>
              <Input
                id="confirm-password"
                type="password"
                {...form.register('confirmPassword', {
                  required: 'Please confirm your password.',
                })}
              />
              {form.formState.errors.confirmPassword && (
                <p className="text-sm text-red-600">{form.formState.errors.confirmPassword.message}</p>
              )}
            </div>

            {message && (
              <div className="flex items-start gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700">
                <CheckCircle2 className="mt-0.5 size-4 shrink-0" />
                <span>{message}</span>
              </div>
            )}
            {error && (
              <div className="flex items-start gap-2 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
                <AlertCircle className="mt-0.5 size-4 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <Button type="submit" className="w-full bg-[#509EE3] hover:bg-[#509EE3]/90 text-white">
              Reset password
            </Button>

            <div className="text-center">
              <button type="button" onClick={onBackToLogin} className="text-sm text-[#509EE3] hover:underline">
                Back to login
              </button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
